## Introduction

The task for this assignment is to create an example using one or more TidyVerse packages, and any dataset from fivethirtyeight.com or Kaggle, create a programming sample "vignette" that demonstrates how to use one or more of the capabilities of the selected TidyVerse package with your selected dataset

The dataset used for this analysis assignment is taken from Kaggle titled "Diabetes Dataset By Age Standardized Countries". The dataset includes information from 200 countries and territories and covers the period from 1980 to 2014. The data is presented in both male and female categories, and estimates are given for different age groups ranging from 20-79 years old. The data is standardized to account for differences in age distributions across countries and over time.

This analysis however will only look into Latin American countries and how the estimated prevalence of diabeete differ across the countries by gender through using the dplyr and ggplot packages part of the tidyverse library.
